"""Add news time

Revision ID: 57d9aa67e013
Revises: a0187ca97cb8
Create Date: 2018-06-24 09:02:18.712701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d9aa67e013'
down_revision = 'a0187ca97cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('time', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'time')
    # ### end Alembic commands ###
