"""Add news hit

Revision ID: a0187ca97cb8
Revises: 1910e133ec36
Create Date: 2018-06-24 09:00:18.678836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0187ca97cb8'
down_revision = '1910e133ec36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('hit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'hit')
    # ### end Alembic commands ###
