"""Add news category

Revision ID: c0d87b2431b7
Revises: f47d0c41ffaa
Create Date: 2018-06-23 11:06:53.100309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d87b2431b7'
down_revision = 'f47d0c41ffaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'news', 'news__category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'category_id')
    # ### end Alembic commands ###
