"""test_add admin

Revision ID: fd66e9d4ef1c
Revises: 2b39b71a361a
Create Date: 2018-06-19 17:29:57.693349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd66e9d4ef1c'
down_revision = '2b39b71a361a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_admin'), 'user', ['admin'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_admin'), table_name='user')
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
